name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  rspec:
    runs-on: ubuntu-latest
    env:
      COVERALLS_REPO_TOKEN: ${{ secrets.github_token }}
    strategy:
      fail-fast: false
      matrix:
        ruby: ["2.7", "3.0", "3.1", "3.2", "3.3"]
    steps:
    - run: |
        echo "Commit msg: ${{ github.event.head_commit.message }}"
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Install Coveralls reporter
      run: |
        curl -L https://github.com/coverallsapp/coverage-reporter/releases/latest/download/coveralls-linux.tar.gz | tar zxv
    - name: Run RSpec
      run: |
        bundle exec rake spec
    - name: Upload coverages to Coveralls
      run: |
        ./coveralls -p --job-flag=ruby-${{ matrix.ruby }}

  rspec_no_vcr:
    name: "rspec:no_vcr"
    needs: rspec
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.3
        bundler-cache: true
    - name: Run RSpec without VCR cassettes
      run: |
        bundle exec rake spec:no_vcr

  coverage:
    needs: rspec
    runs-on: ubuntu-latest
    env:
      COVERALLS_REPO_TOKEN: ${{ secrets.github_token }}
    steps:
    - name: Install Coveralls reporter
      run: |
        curl -L https://github.com/coverallsapp/coverage-reporter/releases/latest/download/coveralls-linux.tar.gz | tar zxv
    - name: Finish Coveralls build
      run: |
        ./coveralls -d
